apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: nx-multitenant
  labels:
    app: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: ruslanguns/client:latest
        ports:
        - containerPort: 80
        # resources:
        #   limits:
        #     cpu: 168Mi
        #     memory: 168Mi
        #   requests:
        #     cpu: 100Mi
        #     memory: 100Mi